name: Percy
on: [push]
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm i @percy/cli
      - run: npx percy snapshot public/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
